### ISSUE TITLE
Text in body of tweet

### ISSUE THREAD

**Issue by moboid** [animalphase/indulgine-twitter-bot#1]
Put the generative text in the body of the tweet as well as in the image.  (better accessibility for vision impaired)

**Comment by lovemecomputer** [comment]
working on this now. need to get tracery variables doing what i want hehe.

optionally we could include the text as the alt/accessibility text on the image but i'm not sure if CBDQ is set up to do this. will check in with v after basic functionality is in place (or let me know if you have an opinion @moboid !)

**Comment by moboid** [comment]
Oh that's a really good question/idea!  Definitely worth asking v.

**Comment by lovemecomputer** [comment]
working through the code, i have to change the structure of how i'm saving out chosen phrases and variables. in pseudocode-ish it needs to me:

```
origin: {{generated text, assigning chosen phrase & words to their own variables}}, svgRoot
svgRoot: {{svg code block, which inserts text in the right places.}} //need to figure out logic for selecting btwn sentence structures?}}
```

it's complicated!! but everything else might rest on this so i'm trying to work through this now!

**Comment by lovemecomputer** [comment]
current state:

![bitmoji](https://render.bitstrips.com/v2/cpanel/d8e66e64-ec9c-495f-947e-9bfe52d2523f-98edfe88-38e8-4a6b-bd23-6f7757eac54b-v1.png?transparent=1&palette=1&width=246)

saving variables works. with an extra layer of nesting, this will make it possible to duplicate the text of the entire sentence:

```
"phrase": [
  "What do machines want? #chosenAdjective.capitalize# #chosenNoun#.",
  "#chosenAdjective.capitalize# #chosenNoun# feel good to computers.",
  "A.I.s can sense #chosenAdjective# #chosenNoun#.",
  "#chosenAdjective.capitalize# #chosenNoun# help machines savor life.",
  "Cyborgs enjoy #chosenAdjective# #chosenNoun#.",
  "Androids dream of #chosenAdjective# #chosenNoun#.",
  "#chosenAdjective.capitalize# #chosenNoun# are what robots crave.",
  "Listen. Bots need #chosenAdjective# #chosenNoun#.",
  "A.I.s like feeling #chosenAdjective# #chosenNoun#.",
  "Of course cyborgs love #chosenAdjective# #chosenNoun#.",
  "#chosenAdjective.capitalize# #chosenNoun# delight machines."
]

, "chosenSentence": ["#phrase# $chosen words: #chosenAdjective# #chosenNoun# "]

,	"origin": ["#[chosenAdjective:#computerAdjective#][chosenNoun:#senseNoun#]chosenSentence#"]

...

```

however, this doesn't solve being able to insert SVG tags in the middle of the sentence… i'm looking into a few things to test… might end tracery to select an index number, then us JS to choose from a plain-text list of phrases, or a marked-up list of phrases, using that same index.  that might not preserve capitalization tho. testing! (if capitalization is the only problem, a simple solution could be lower-case everything :) )

**Comment by moboid** [comment]
lower casing could be kind of cute.  :)

**Comment by moboid** [comment]
(I know that capitalization does change the way a text reader will pronounce a word, but that's probably not problematic here.)

**Comment by moboid** [comment]
OK I just tested that theory using apple's text-to-speech, and caps don't seem to affect the pronunciation of a word (as long as the punctuation remains the same.)  Aesthetically, keeping caps is WAY better though.  So, see what you find out.

**Comment by lovemecomputer** [comment]
cool! okay so………… it's kinda of working. there is currently no logic for word-wrapping in place. there are multiple options, none of them great, so i'll see what is the best way to do this and get it running stable on the bot server. for now we've got text here in both body and image!

<img width="1070" alt="screen shot 2018-07-22 at 15 11 32" src="https://user-images.githubusercontent.com/3846271/43049708-e3d80a50-8dc1-11e8-8fe1-645d2bc9084c.png">

so, capitalization works arlight with this!! however newline characters work in text, but when put inside the svg code, cause CBDQ to not parse it as svg and just insert all the SVG text into the page. finding a way to get newline characters into the text might be all we need to do if there's a way! if nothing else,  perhaps using javascript that runs after the text has finished rendering… or even more next variables with multiple parts of sentences……

**Comment by lovemecomputer** [comment]
going to mark this issue as complete, and add a more specific issue for the other issues around formatting text.
