### ISSUE TITLE
Lines need to be darker/stronger

### ISSUE THREAD

**Issue by moboid** [animalphase/indulgine-twitter-bot#2]
The line weight is often too light, especially on the curvy line.  When the images are rendered down for twitter preview, they disappear.

**Comment by lovemecomputer** [comment]
higher line frequency may help make this look better in the preview… will look at alternate kinds of lines we could put in there. i still thing the super-thing pencil-like lines look really good in full-size

**Comment by lovemecomputer** [comment]
okay, i think this (plus playing with trying other filters on each line) will be a good activity for our 'final probablities pass'
