### ISSUE TITLE
Up the average frequency of lines

### ISSUE THREAD

**Issue by moboid** [animalphase/indulgine-twitter-bot#3]
Seems like right now the average number of lines is too low.  It's good that sometimes there is just one or two lines, but it should be on average more than that.   maybe like 5 lines average?  (if you want to tell me where in code this is set, you can reassign back to me and I'll play aroudn with it.)

**Comment by lovemecomputer** [comment]
cool! overall i think we have a few things of probability that we can mess with. i will group all of these together as much as possible, and we can tweak these probabilities after all the features are in place!

**Comment by lovemecomputer** [comment]
frequency is somewhat updated. we can also tweak different kinds of "sets" of lines by adding variations to the `pathGroup` setting

**Comment by lovemecomputer** [comment]
closing this issue and adding the the general "probability pass" issue
