### ISSUE TITLE
Add Text repetition

### ISSUE THREAD

**Issue by moboid** [animalphase/indulgine-twitter-bot#4]
Let's get the lovely text repetition going for the second line.  As per the local prototype version.

**Comment by lovemecomputer** [comment]
the prototype version also aligns horizontal lines with each duplicated line of text. currently planning out the best way to implement this, as well as incrementing the height of each line. might have to use some magic numbers and weird hard-coded alternatives

**Comment by lovemecomputer** [comment]
implemented
![bitmoji](https://render.bitstrips.com/v2/cpanel/e99091d0-043e-4f09-af06-62a0d62eb583-98edfe88-38e8-4a6b-bd23-6f7757eac54b-v1.png?transparent=1&palette=1&width=246)
