### ISSUE TITLE
final pass of probabilities

### ISSUE THREAD

**Issue by lovemecomputer** [animalphase/indulgine-twitter-bot#9]
check probabilities for:
- background lines
  - `pathGroup`
- italic text or not
  - `italicStyle`
- likelihood & amount of warping on text
  - [referenced in this issue](https://github.com/animalphase/indulgine-twitter-bot/issues/7)

**Comment by moboid** [comment]
Notes for probability tweaking:
- Amount of blurriness (set a min/max)
- Probability that all background markings are empty/null (shouldn't happen?)

Questions:
- Is repetition working?
- Outline?
-

**Comment by lovemecomputer** [comment]
done :)
![bitmoji](https://render.bitstrips.com/v2/cpanel/e99091d0-043e-4f09-af06-62a0d62eb583-98edfe88-38e8-4a6b-bd23-6f7757eac54b-v1.png?transparent=1&palette=1&width=246)
